<cfset greeting = "Hello World!!">
<cfscript>
      Access_Control = ["ACCESS CONTROL POLICY AND PROCEDURES", "ACCOUNT MANAGEMENT", "ACCESS ENFORCEMENT",
      "INFORMATION FLOW ENFORCEMENT",
      "SEPARATION OF DUTIES",
      "LEAST PRIVILEGE",
      "UNSUCCESSFUL LOGON ATTEMPTS",
      "SYSTEM USE NOTIFICATION",
      "PREVIOUS LOGON (ACCESS) NOTIFICATION",
      "CONCURRENT SESSION CONTROL",
      "SESSION LOCK",
      "SESSION TERMINATION",
      "SUPERVISION AND REVIEW   ACCESS CONTROL",
      "PERMITTED ACTIONS WITHOUT IDENTIFICATION OR AUTHENTICATION",
      "AUTOMATED MARKING",
      "SECURITY ATTRIBUTES",
      "REMOTE ACCESS",
      "WIRELESS ACCESS",
      "ACCESS CONTROL FOR MOBILE DEVICES",
      "USE OF EXTERNAL INFORMATION SYSTEMS",
      "INFORMATION SHARING",
      "PUBLICLY ACCESSIBLE CONTENT",
      "DATA MINING PROTECTION",
      "ACCESS CONTROL DECISIONS",
      "REFERENCE MONITOR"
      "SECURITY AWARENESS AND TRAINING POLICY AND PROCEDURES",
      Awareness And Training = ["SECURITY AWARENESS TRAINING", "ROLE-BASED SECURITY TRAINING",
      "SECURITY TRAINING RECORDS",
      "CONTACTS WITH SECURITY GROUPS AND ASSOCIATIONS"
      "AUDIT AND ACCOUNTABILITY POLICY AND PROCEDURES",Audit And Accountability
      "AUDIT EVENTS",
      "CONTENT OF AUDIT RECORDS",
      "AUDIT STORAGE CAPACITY",
      "RESPONSE TO AUDIT PROCESSING FAILURES",
      "AUDIT REVIEW, ANALYSIS, AND REPORTING",
      "AUDIT REDUCTION AND REPORT GENERATION",
      "TIME STAMPS",
      "PROTECTION OF AUDIT INFORMATION",
      "NON-REPUDIATION",
      "AUDIT RECORD RETENTION",
      "AUDIT GENERATION",
      "MONITORING FOR INFORMATION DISCLOSURE",
      "SESSION AUDIT",
      "ALTERNATE AUDIT CAPABILITY",
      "CROSS-ORGANIZATIONAL AUDITING"
      "SECURITY ASSESSMENT AND AUTHORIZATION POLICY AND PROCEDURES",Security Assessment And Authorization
      "SECURITY ASSESSMENTS",
      "SYSTEM INTERCONNECTIONS",
      "SECURITY CERTIFICATION",
      "PLAN OF ACTION AND MILESTONES",
      "SECURITY AUTHORIZATION",
      "CONTINUOUS MONITORING",
      "PENETRATION TESTING",
      "INTERNAL SYSTEM CONNECTIONS"
      "CONFIGURATION MANAGEMENT POLICY AND PROCEDURES",Configuration Management
      "BASELINE CONFIGURATION",
      "CONFIGURATION CHANGE CONTROL",
      "SECURITY IMPACT ANALYSIS",
      "ACCESS RESTRICTIONS FOR CHANGE",
      "CONFIGURATION SETTINGS",
      "LEAST FUNCTIONALITY",
      "INFORMATION SYSTEM COMPONENT INVENTORY",
      "CONFIGURATION MANAGEMENT PLAN",
      "SOFTWARE USAGE RESTRICTIONS",
      "USER-INSTALLED SOFTWARE"
      "CONTINGENCY PLANNING POLICY AND PROCEDURES",Contingency Planning
      "CONTINGENCY PLAN",
      "CONTINGENCY TRAINING",
      "CONTINGENCY PLAN TESTING",
      "CONTINGENCY PLAN UPDATE",
      "ALTERNATE STORAGE SITE",
      "ALTERNATE PROCESSING SITE",
      "TELECOMMUNICATIONS SERVICES",
      "INFORMATION SYSTEM BACKUP",
      "INFORMATION SYSTEM RECOVERY AND RECONSTITUTION",
      "ALTERNATE COMMUNICATIONS PROTOCOLS",
      "SAFE MODE",
      "ALTERNATIVE SECURITY MECHANISMS"
      "IDENTIFICATION AND AUTHENTICATION POLICY AND PROCEDURES",Identification And Authentication
      "IDENTIFICATION AND AUTHENTICATION (ORGANIZATIONAL USERS)",
      "DEVICE IDENTIFICATION AND AUTHENTICATION",
      "IDENTIFIER MANAGEMENT",
      "AUTHENTICATOR MANAGEMENT",
      "AUTHENTICATOR FEEDBACK",
      "CRYPTOGRAPHIC MODULE AUTHENTICATION",
      "IDENTIFICATION AND AUTHENTICATION (NON-ORGANIZATIONAL USERS)",
      "SERVICE IDENTIFICATION AND AUTHENTICATION",
      "ADAPTIVE IDENTIFICATION AND AUTHENTICATION",
      "RE-AUTHENTICATION"
      "INCIDENT RESPONSE POLICY AND PROCEDURES",Incident Response
      "INCIDENT RESPONSE TRAINING",
      "INCIDENT RESPONSE TESTING",
      "INCIDENT HANDLING",
      "INCIDENT MONITORING",
      "INCIDENT REPORTING",
      "INCIDENT RESPONSE ASSISTANCE",
      "INCIDENT RESPONSE PLAN",
      "INFORMATION SPILLAGE RESPONSE",
      "INTEGRATED INFORMATION SECURITY ANALYSIS TEAM"
      "SYSTEM MAINTENANCE POLICY AND PROCEDURES",Maintenance
      "CONTROLLED MAINTENANCE",
      "MAINTENANCE TOOLS",
      "NONLOCAL MAINTENANCE",
      "MAINTENANCE PERSONNEL",
      "TIMELY MAINTENANCE"
      "MEDIA PROTECTION POLICY AND PROCEDURES",Media Protection
      "MEDIA ACCESS",
      "MEDIA MARKING",
      "MEDIA STORAGE",
      "MEDIA TRANSPORT",
      "MEDIA SANITIZATION",
      "MEDIA USE",
      "MEDIA DOWNGRADING"
      "PHYSICAL AND ENVIRONMENTAL PROTECTION POLICY AND PROCEDURES",Physical And Environmental Protection
      "PHYSICAL ACCESS AUTHORIZATIONS",
      "PHYSICAL ACCESS CONTROL",
      "ACCESS CONTROL FOR TRANSMISSION MEDIUM",
      "ACCESS CONTROL FOR OUTPUT DEVICES",
      "MONITORING PHYSICAL ACCESS",
      "VISITOR CONTROL",
      "VISITOR ACCESS RECORDS",
      "POWER EQUIPMENT AND CABLING",
      "EMERGENCY SHUTOFF",
      "EMERGENCY POWER",
      "EMERGENCY LIGHTING",
      "FIRE PROTECTION",
      "TEMPERATURE AND HUMIDITY CONTROLS",
      "WATER DAMAGE PROTECTION",
      "DELIVERY AND REMOVAL",
      "ALTERNATE WORK SITE",
      "LOCATION OF INFORMATION SYSTEM COMPONENTS",
      "INFORMATION LEAKAGE",
      "ASSET MONITORING AND TRACKING"
      "SECURITY PLANNING POLICY AND PROCEDURES",Planning
      "SYSTEM SECURITY PLAN",
      "SYSTEM SECURITY PLAN UPDATE",
      "RULES OF BEHAVIOR",
      "PRIVACY IMPACT ASSESSMENT",
      "SECURITY-RELATED ACTIVITY PLANNING",
      "SECURITY CONCEPT OF OPERATIONS",
      "INFORMATION SECURITY ARCHITECTURE",
      "CENTRAL MANAGEMENT"
      "PERSONNEL SECURITY POLICY AND PROCEDURES",Personnel Security
      "POSITION RISK DESIGNATION",
      "PERSONNEL SCREENING",
      "PERSONNEL TERMINATION",
      "PERSONNEL TRANSFER",
      "ACCESS AGREEMENTS",
      "THIRD-PARTY PERSONNEL SECURITY",
      "PERSONNEL SANCTIONS"
      "RISK ASSESSMENT POLICY AND PROCEDURES",Risk Assessment
      "SECURITY CATEGORIZATION",
      "RISK ASSESSMENT",
      "RISK ASSESSMENT UPDATE",
      "VULNERABILITY SCANNING",
      "TECHNICAL SURVEILLANCE COUNTERMEASURES SURVEY"
      "SYSTEM AND SERVICES ACQUISITION POLICY AND PROCEDURES",System And Services Acquisition
      "ALLOCATION OF RESOURCES",
      "SYSTEM DEVELOPMENT LIFE CYCLE",
      "ACQUISITION PROCESS",
      "INFORMATION SYSTEM DOCUMENTATION",
      "SOFTWARE USAGE RESTRICTIONS",
      "USER-INSTALLED SOFTWARE",
      "SECURITY ENGINEERING PRINCIPLES",
      "EXTERNAL INFORMATION SYSTEM SERVICES",
      "DEVELOPER CONFIGURATION MANAGEMENT",
      "DEVELOPER SECURITY TESTING AND EVALUATION",
      "SUPPLY CHAIN PROTECTION",
      "TRUSTWORTHINESS",
      "CRITICALITY ANALYSIS",
      "DEVELOPMENT PROCESS, STANDARDS, AND TOOLS",
      "DEVELOPER-PROVIDED TRAINING",
      "DEVELOPER SECURITY ARCHITECTURE AND DESIGN",
      "TAMPER RESISTANCE AND DETECTION",
      "COMPONENT AUTHENTICITY",
      "CUSTOMIZED DEVELOPMENT OF CRITICAL COMPONENTS",
      "DEVELOPER SCREENING",
      "UNSUPPORTED SYSTEM COMPONENTS"
      "SYSTEM AND COMMUNICATIONS PROTECTION POLICY AND PROCEDURES",System And Communications Protection
      "APPLICATION PARTITIONING",
      "SECURITY FUNCTION ISOLATION",
      "INFORMATION IN SHARED RESOURCES",
      "DENIAL OF SERVICE PROTECTION",
      "RESOURCE AVAILABILITY",
      "BOUNDARY PROTECTION",
      "TRANSMISSION CONFIDENTIALITY AND INTEGRITY",
      "TRANSMISSION CONFIDENTIALITY",
      "NETWORK DISCONNECT",
      "TRUSTED PATH",
      "CRYPTOGRAPHIC KEY ESTABLISHMENT AND MANAGEMENT",
      "CRYPTOGRAPHIC PROTECTION",
      "PUBLIC ACCESS PROTECTIONS",
      "COLLABORATIVE COMPUTING DEVICES",
      "TRANSMISSION OF SECURITY ATTRIBUTES",
      "PUBLIC KEY INFRASTRUCTURE CERTIFICATES",
      "MOBILE CODE",
      "VOICE OVER INTERNET PROTOCOL",
      "SECURE NAME / ADDRESS RESOLUTION SERVICE (AUTHORITATIVE SOURCE)",
      "SECURE NAME / ADDRESS RESOLUTION SERVICE (RECURSIVE OR CACHING RESOLVER)",
      "ARCHITECTURE AND PROVISIONING FOR NAME / ADDRESS RESOLUTION SERVICE",
      "SESSION AUTHENTICITY",
      "FAIL IN KNOWN STATE",
      "THIN NODES",
      "HONEYPOTS",
      "PLATFORM-INDEPENDENT APPLICATIONS",
      "PROTECTION OF INFORMATION AT REST",
      "HETEROGENEITY",
      "CONCEALMENT AND MISDIRECTION",
      "COVERT CHANNEL ANALYSIS",
      "INFORMATION SYSTEM PARTITIONING",
      "TRANSMISSION PREPARATION INTEGRITY",
      "NON-MODIFIABLE EXECUTABLE PROGRAMS",
      "HONEYCLIENTS",
      "DISTRIBUTED PROCESSING AND STORAGE",
      "OUT-OF-BAND CHANNELS",
      "OPERATIONS SECURITY",
      "PROCESS ISOLATION",
      "WIRELESS LINK PROTECTION",
      "PORT AND I/O DEVICE ACCESS",
      "SENSOR CAPABILITY AND DATA",
      "USAGE RESTRICTIONS",
      "DETONATION CHAMBERS"
      "SYSTEM AND INFORMATION INTEGRITY POLICY AND PROCEDURES",System And Information Integrity
      "FLAW REMEDIATION",
      "MALICIOUS CODE PROTECTION",
      "INFORMATION SYSTEM MONITORING",
      "SECURITY ALERTS, ADVISORIES, AND DIRECTIVES",
      "SECURITY FUNCTION VERIFICATION",
      "SOFTWARE, FIRMWARE, AND INFORMATION INTEGRITY",
      "SPAM PROTECTION",
      "INFORMATION INPUT RESTRICTIONS",
      "INFORMATION INPUT VALIDATION",
      "ERROR HANDLING",
      "INFORMATION HANDLING AND RETENTION",
      "PREDICTABLE FAILURE PREVENTION",
      "NON-PERSISTENCE",
      "INFORMATION OUTPUT FILTERING",
      "MEMORY PROTECTION",
      "FAIL-SAFE PROCEDURES"
      "INFORMATION SECURITY PROGRAM PLAN",Program Management
      "SENIOR INFORMATION SECURITY OFFICER",
      "INFORMATION SECURITY RESOURCES",
      "PLAN OF ACTION AND MILESTONES PROCESS",
      "INFORMATION SYSTEM INVENTORY",
      "INFORMATION SECURITY MEASURES OF PERFORMANCE",
      "ENTERPRISE ARCHITECTURE",
      "CRITICAL INFRASTRUCTURE PLAN",
      "RISK MANAGEMENT STRATEGY",
      "SECURITY AUTHORIZATION PROCESS",
      "MISSION/BUSINESS PROCESS DEFINITION",
      "INSIDER THREAT PROGRAM",
      "INFORMATION SECURITY WORKFORCE",
      "TESTING, TRAINING, AND MONITORING",
      "CONTACTS WITH SECURITY GROUPS AND ASSOCIATIONS"
</cfscript>

<html>
<head>
</head>
<body>

      <p>HTML</p>
            <p>More HTML</p>

            <p>#greeting#</p>

            <p>#ucase(greeting)#</p>

      </cfoutput>
     <cfdump var="#greeting#>


<body>
</html>
